lsi: false
safe: true
source: [https://github.com/suf102/Sufyan-Portfolio]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minima
exclude: ['Hackathons/MEV_Hackathon/README.md']